### PR TITLE
Add new reporting plugin that will provide JSON output to the terminal and/or to a file. This new plugin will make the existing print_json reporting plugin obsolete.

### PR DESCRIPTION
**Pull request by tdenewiler**

### CODE REVIEW

**Comment by tdenewiler** [comment]
To test locally I did the following.

Create `statick_tool/rsc/x.yaml`.

```yaml
default: x
```

Create `statick_tool/rsc/y.yaml`.

```yaml
levels:
  x:
    discovery:
      ros:
    reporting:
      json:
        terminal: "True"
        files: "True"
    tool:
      - catkin_lint
```

Run the following.

```shell
statick . --output-directory /tmp/x --log info --user-paths statick_tool/ --profile x.yaml --config y.yaml
```

1. Verify that `/tmp/x/statick-x/statick-x.json` is created and has an empty list of issues.
2. Verify that an empty list of issues are printed to the terminal in JSON format.
3. Edit `y.yaml` to comment out or set `files` and `terminal` to `False` and verify that that particular report type is not generated.

**Comment by tdenewiler** [comment]
@jhdcs feel free to try this out if you like.

**Comment by tdenewiler** [comment]
Fixes #352.

**Comment by xydesa** [comment]
When I run this on a ros workspace using the `-ws` statick flag I do not get any issues from this new plugin printed out or in the directory associated with the final `all_packages` meta package. I do see them from the `print_to_console` reporting plugin and the other reporting plugins.

**Comment by xydesa** [comment]
If I forget to add the "terminal" or "files" sub-attributes for this plugin, I get the following exception (running with -ws or not):
```
~/code/github/statick_ws/tdenewiler-statick/statick ./src -ws --output-directory /tmp/statick-output --user-paths ./statick_config --profile x.yaml --config y.yaml --log info
INFO:root:Log level set to INFO
INFO:root:-- Scanning 18 packages --
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/statick.py", line 625, in scan_package
    issues, dummy = self.run(package.path, parsed_args)
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/statick.py", line 438, in run
    plugin.report(package, issues, level)
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/plugins/reporting/json_reporting_plugin.py", line 37, in report
    file_output_str = self.plugin_context.config.get_reporting_config(
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/config.py", line 131, in get_reporting_config
    return self.get_plugin_config("reporting", plugin, level, key, default)
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/config.py", line 106, in get_plugin_config
    if key in plugin_config:
TypeError: argument of type 'NoneType' is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick", line 50, in <module>
    main()
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick", line 37, in main
    _, success = statick.run_workspace(parsed_args)
  File "/home/axydes/code/github/statick_ws/tdenewiler-statick/statick_tool/statick.py", line 530, in run_workspace
    total_issues = pool.starmap(self.scan_package, mp_args)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
TypeError: argument of type 'NoneType' is not iterable

```

**Comment by tdenewiler** [comment]
@xydesa you found an underlying bug. I fixed it in 150da45. When both `terminal` and `files` were commented out the `plugin_config` was None but we still tried to access it. I'm still looking into the printing part when `-ws` is specified. If I set `--log info` I see the json output printed as part of the logging module, but not a straight print like it should be.

**Review by xydesa — APPROVED** [review]
LGTM and it now works for me.

**Pull request merged**
