### PR TITLE
Add python3 compatibility, testing to Statick

### PR DESCRIPTION
**Pull request by creffett**

### CODE REVIEW

**Comment by tdenewiler** [comment]
On Travis the pypy3.5 build has the following:

    SKIPPED:  pypy35: InterpreterNotFound: pypy3.5

It still says `Congratulations :)`, but that seems like it is not doing what you want.

**Comment by creffett** [comment]
Thanks, missed that. Will have a look.

**Comment by tdenewiler** [comment]
When I run the following locally on a Mint 18.2 OS (Ubuntu 16.04 based) I get errors:

    ./statick . statick_output/ --profile self_check.yaml

```
Tool pylint: 14 unique issues
  /home/thomas/src/reffett_statick/setup.py:6: pylint:E0012(bad-option-value): Bad option value 'bare-except # noqa: E722' [5]
  /home/thomas/src/reffett_statick/setup.py:6: pylint:W0702(bare-except): No exception type(s) specified [5]
  /home/thomas/src/reffett_statick/statick:26: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick:29: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:31: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:57: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:66: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:70: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:76: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:78: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:84: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_ws:85: pylint:C0325(superfluous-parens): Unnecessary parens after 'print' keyword [5]
  /home/thomas/src/reffett_statick/statick_tool/plugins/discovery/cmake_discovery_plugin.py:72: pylint:C0301(line-too-long): Line too long (116/100) [5]
  /home/thomas/src/reffett_statick/statick_tool/plugins/discovery/cmake_discovery_plugin.py:78: pylint:C0301(line-too-long): Line too long (101/100) [5]
```

I'll attach a diff showing how I fixed all of them. We don't have to accept all the changes I made. You can apply it or I can open a PR for you -- whatever is easiest.

**Comment by creffett** [comment]
Added your change and ended up striking pypy3 since I can't figure out how to make it behave. Once this latest push builds, clear to merge at your convenience.

**Pull request merged**
