### PR TITLE
Updated configs to use list format for 'inherits_from'

### PR DESCRIPTION
**Pull request by gregtkogut**

### CODE REVIEW

**Comment by tdenewiler** [comment]
I got the unit tests to pass with the following diff.

```shell
diff --git a/statick_tool/config.py b/statick_tool/config.py
index 2f207fd..a6fd41f 100644
--- a/statick_tool/config.py
+++ b/statick_tool/config.py
@@ -135,11 +135,12 @@ class Config:
                 )
             configs = ""
             for inherited_level in self.config["levels"][level]["inherits_from"]:
-                config = self.get_plugin_config(
-                    plugin_type, plugin, inherited_level, key, default
-                )
-                if config is not None:
-                    configs += config
+                if level is not inherited_level:
+                    config = self.get_plugin_config(
+                        plugin_type, plugin, inherited_level, key, default
+                    )
+                    if config is not None:
+                        configs += config
             if configs:
                 return configs
         return default
```

**Comment by denewiler** [comment]
Looks like you need to merge in main again. Main now has your fix to the mypy issue causing workflow issues in this PR.

**Comment by gregtkogut** [comment]
@denewiler, your diff caused a drop in coverage...I'll take a look at that later, but feel free to push another diff if you feel you can do it quicker, being more familiar with the testing.

**Comment by gregtkogut** [comment]
Unfortunately every time I revisit this there's something new broken....any insight with the tox failure?   I ran the the Statick check on the main branch too, and get the same thing, so it's probably unrelated to this PR.

**Comment by tdenewiler** [comment]
The tox errors are new for the main branch. I'll take a look. Note that there is an open PR that fixes coverage for the `update_inherits` branch. The PR is at https://github.com/gregtkogut/statick/pull/1 and is waiting on permission for actions to run.

**Comment by tdenewiler** [comment]
Found the culprit at https://github.com/tholo/pytest-flake8/issues/87. The upgrade to flake8 v5 broke pytest-flake8 to give the error we are seeing.

```shell
AttributeError: module 'flake8.options.config' has no attribute 'ConfigFileFinder'
```

I have a one-line fix working in Windows, will PR soon if Actions pass.

**Comment by gregtkogut** [comment]
> The tox errors are new for the main branch. I'll take a look. Note that there is an open PR that fixes coverage for the `update_inherits` branch. The PR is at [gregtkogut#1](https://github.com/gregtkogut/statick/pull/1) and is waiting on permission for actions to run.

Thanks, hadn't seen that PR.  Waiting on your 1-line fix to pass the Action for both that PR and then eventually this one.

**Comment by gregtkogut** [comment]
Thanks for the help,  I think this is finally ready.

**Review by denewiler — APPROVED** [review]

**Pull request merged**
