### PR TITLE
Use tox for code checking

### PR DESCRIPTION
**Pull request by creffett**
Most of these changes are things like import order sorting or pep8 cleanups so that the tox tests actually pass. I went with the following pytest plugins:
* pytest-cov
* pytest-flake8
* pytest-isort
* pytest-pep257

If there are any you don't like in there, I'm fine with changing that list, it was just based on the plugins I've used on other projects. Reason we're using tox + pytest is to lay the ground work for actual unit testing and multi-python tests in the future.

### CODE REVIEW

**Comment by tdenewiler** [comment]
I just did a quick look at the diff and nothing jumped out at me. All those changes to files look good. I'll review it more in depth soon. Looking at tox will take me a bit longer since I have not used it before. I'm excited to see a buildup to actual testing. Thanks!

**Comment by creffett** [comment]
The general idea is that it spins up a virtualenv for each of several python versions (and I think it can also matrix with other versions, so you could do, say, several python version x several django versions for a webapp), and then runs tests and such for each of them. This way, we can test that Statick works with multiple Python versions in the future (and I should have a merge request for Python 3 compatibility pretty soon after this is merged)

**Comment by tdenewiler** [comment]
I am having an issue with the cmake discovery plugin that affects the catkin-format tool plugin. I could likely make a more minimal example, but I am running against my [node_example](https://github.com/tdenewiler/node_example) package. I have that at `~/src/node_example/src/node_example`. For each of the master and tox branches I run the following:

    ./statick ~/src/node_example/src/node_example/ statick_output/ --user-paths ~/src/node_example/src/node_example/statick_config/ --force-tool-list=clang-format

The master branch is fine, but I get the following error on the tox branch:

```
Running clang-format tool plugin...
Traceback (most recent call last):
  File "./statick", line 34, in <module>
    main()
  File "./statick", line 24, in main
    issues, success = statick.run(path, parsed_args)
  File "/home/thomas/tmp/statick/statick_tool/statick.py", line 212, in run
    tool_issues = plugin.scan(package, level)
  File "/home/thomas/tmp/statick/statick_tool/plugins/tool/clang_format_tool_plugin.py", line 46, in scan
    flags = ["-header-filter=" + package["src_dir"] + "/.*", "-p",
KeyError: 'src_dir'
```

I grabbed the `statick_tool/plugins/discovery/cmake_discovery_plugin.py` file from master branch and copied that over the modified version in the tox branch. Running with that single reverted file in the tox branch I did not get any errors -- the output matched the output from running the master branch.

I have not looked into what the syntax changes in that file are doing yet. I'll try to investigate more later. If you have any ideas please let me know.

Everything else in this PR looks good to me so far. I'll run a couple more tests on my side to see if anything else pops up.

**Comment by tdenewiler** [comment]
Note that I got the same clang-format errors when I ran without `--force-tool-list=clang-format`. It is just much faster to run with that flag.

**Comment by creffett** [comment]
Got it, I'll have a look.

**Pull request merged**
